import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Modak } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choisis ce dont tu as besoin
  variable: "--font-poppins",
})

const modak = Modak({
  subsets: ["latin"],
  weight: "400", // Modak n’a qu’un seul poids
  variable: "--font-modak",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${modak.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
